# This file is generated by Dist::Zilla::Plugin::CPANFile v6.024
# Do not edit this file directly. To change prereqs, edit the `dist.ini` file.

requires "Moo" => "2.005004";
requires "perl" => "5.014";

on 'test' => sub {
  requires "Moo" => "2.005004";
  requires "perl" => "5.014";
};

on 'configure' => sub {
  requires "ExtUtils::MakeMaker" => "0";
};
