#!/bin/bash

# Check the repo is in ready-state
if [[ -n $(git status --porcelain) ]]; then
  echo "Uncommitted changes!" && exit 0;
fi

# Delete existing release tag (if exists)
git tag -d cpan 2> /dev/null
git push origin :refs/tags/cpan 2> /dev/null

# Push archival release tag
git tag cpan
git push --tags
