#!/bin/bash

export V=$1
export DZIL_RELEASE=0
export RENDER=1

# Ensure release version is explicit
if [ ! -n "$V" ]; then
  echo 'No release version!' && exit 0;
fi

# Check the repo is in ready-state
if ! git diff-index --quiet HEAD --; then
  echo "Uncommitted changes!" && exit 0;
fi

# Test fake build before build
if ! dzil test; then
  echo "Build test failed!" && exit 0;
fi

# Cleanup build
dzil clean

# Build Package
dzil build

# Commit generated POD changes
if ! git diff-index --quiet HEAD --; then
  git checkout CHANGES && git add . && git commit -m 'Update documentation'
fi