#!/bin/bash

export DZIL_RELEASE=0
export RENDER=1

# Check the repo is in ready-state
if ! git diff-index --quiet HEAD --; then
  echo "Uncommitted changes!" && exit 0;
fi

# Build Package
dzil build

# Push generated POD changes
if ! git diff-index --quiet HEAD --; then
  git checkout CHANGES && git add . && git commit -m 'Update documentation'
fi