#!/bin/bash

# Repo URL to base links off of
REPOSITORY_URL=https://github.com/cpanery/venus

# Get a list of all tags in reverse order
# Assumes the tags are in version format like v1.2.3
GIT_TAGS=$(git tag -l --sort=-version:refname)

# Make the tags an array
TAGS=($GIT_TAGS)
LATEST_TAG=${TAGS[0]}
PREVIOUS_TAG=${TAGS[1]}

# Uncomment if you want to specify your own two tags to compare
# LATEST_TAG=v0.23.1
# PREVIOUS_TAG=v0.22.0

# Get a log of commits that occured between two tags
COMMITS=$(git log $PREVIOUS_TAG..$LATEST_TAG --pretty=format:"%H")

# Store our changelog in a variable to be saved to a file at the end
MARKDOWN="## Version [${LATEST_TAG}]($REPOSITORY_URL/compare/$PREVIOUS_TAG...$LATEST_TAG)"
MARKDOWN+='\n'

# Loop over each commit and look for merged pull requests
for COMMIT in $COMMITS; do
  # Get the subject of the current commit
  SUBJECT=$(git log -1 ${COMMIT} --pretty=format:"%s")

  # If the subject contains "... (#xxxxx)" then it is deemed a pull request
  PULL_REQ=$(grep -Eo "\(#[[:digit:]]+\)$" <<< "$SUBJECT")
  PULL_NUM=$(grep -Eo '\d+' <<< "$PULL_REQ")
  PULL_TXT=$(echo "$SUBJECT" | sed -E 's/ \(#.*\)$//')

  if [[ $PULL_REQ ]]; then
  # Get the body of the commit
  # !!! BODY=$(git log -1 ${COMMIT} --pretty=format:'%b')
  MARKDOWN+='\n'
  MARKDOWN+=" - $PULL_TXT ([#$PULL_NUM]($REPOSITORY_URL/pull/$PULL_NUM))"
  fi
done

# Save our markdown to a file
echo -e "$MARKDOWN" > LATEST.md
