#!/bin/bash

export V=$1
export DZIL_RELEASE=1
export RENDER=1

# Ensure release version is explicit
if [ ! -n "$V" ]; then
  echo 'No release version!' && exit 0;
fi

# Check the repo is in ready-state
if [[ -n $(git status --porcelain) ]]; then
  echo "Uncommitted changes!" && exit 0;
fi

# Test source before build
if ! prove -r t; then
  echo "Test suite failed!" && exit 0;
fi

# Delete existing release tag (if exists)
git tag -d $V 2> /dev/null
git push origin :refs/tags/$V 2> /dev/null

# Persist release version
echo $V > VERSION

# Check the repo is in ready-state
if [[ -n $(git status --porcelain) ]]; then
  echo "Uncommitted changes!" && exit 0;
fi

# Cleanup build
dzil clean

# Build Package
dzil build

# Check the repo is in ready-state
if [[ -n $(git status --porcelain) ]]; then
  echo "Uncommitted changes!" && exit 0;
fi

# Tag as $version for releasing
git tag $(cat VERSION) 2> /dev/null

# Re-push all tags (just in case)
git push --tags 2> /dev/null