#!/bin/bash

export V=$1
export DZIL_RELEASE=1
export RENDER=1

# Ensure release version is explicit
if [ ! -n "$V" ]; then
  echo 'No release version!' && exit 0;
fi

# Check the repo is in ready-state
if ! git diff-index --quiet HEAD --; then
  echo "Uncommitted changes!" && exit 0;
fi

# Persist release version
echo $V > VERSION

# Test fake build before build
if ! dzil test; then
  echo "Build test failed!" && exit 0;
fi

# Cleanup build
dzil clean

# Delete existing release tag (if exists)
git tag -d $V 2> /dev/null
git push origin :refs/tags/$V 2> /dev/null

# Commit updated release version
if ! git diff-index --quiet HEAD --; then
  git add . && git commit -m 'Update version'
fi

# Build Package
dzil build

# Commit generated POD changes
if ! git diff-index --quiet HEAD --; then
  git add . && git commit -m 'Update documentation'
fi

# Tag as $version for releasing
git tag $(cat VERSION) 2> /dev/null

# Re-push all tags (just in case)
git push --tags 2> /dev/null