#!/usr/bin/env perl

package main;

use 5.018;

use strict;
use warnings;

use Cwd ();
use File::Spec ();

our $LLIB;
our @PATH;

BEGIN {
  $ENV{VENUS_TASK_RUN} = 1;
  $ENV{VENUS_RUN_NAME} = 'vns';
}

BEGIN {
  @PATH = File::Spec->splitdir(Cwd::realpath($0));
  $LLIB = File::Spec->catfile(@PATH[0..$#PATH-2], 'lib');
}

use lib "$LLIB";

use Venus::Run;

1;
