#!/usr/bin/env perl

package main;

use 5.018;

use strict;
use warnings;

use Cwd ();
use File::Spec ();

our $REPO;
our @PATH;

BEGIN {
  $ENV{VENUS_TASK_RUN} = 1;
  $ENV{VENUS_RUN_NAME} = 'vns';
}

BEGIN {
  @PATH = File::Spec->splitdir(Cwd::realpath($0));
  $REPO = File::Spec->catfile(splice(@PATH, 0, -2), 'lib');
}

use lib "$REPO";

use Venus::Run;

1;
