#!/usr/bin/env perl

package main;

use 5.018;

use strict;
use warnings;

use Cwd ();
use File::Spec ();

our $REPO;
our @PATH;

BEGIN {
  $ENV{VENUS_TASK_AUTO} = 1;
  $ENV{VENUS_TASK_NAME} = 'vns';
}

BEGIN {
  @PATH = File::Spec->splitdir(Cwd::realpath($0));
  $HOME = File::Spec->catfile(splice(@PATH, 0, -2), 'lib');
}

use lib "$HOME";

use Venus::Run;

1;
