name: Archiving

on:
  push:
    tags:
    - cpan

jobs:
  Archive:
    runs-on: ubuntu-latest
    container:
      image: perl:5.32

    steps:
    - uses: actions/checkout@v2
    - name: Setup Git User
      run: git config --global user.name "Cpanery"
    - name: Setup Git Email
      run: git config --global user.email "cpanery@cpan.org"
    - name: Setup GitHub User
      run: git config --global github.user ${{ secrets.GithubUser }}
    - name: Setup GitHub Token
      run: git config --global github.token ${{ secrets.GithubToken }}
    - name: Advertise Perl Version
      run: perl -V
    - name: Install Dist::Zilla
      run: cpanm -qn Dist::Zilla
    - name: Install Dist::Zilla Dependencies
      run: dzil authordeps | cpanm -qn
    - name: Install Project Dependencies
      run: cpanm -qn --reinstall --installdeps .
    - name: Cleanup Environment
      run: dzil clean
    - name: Build Distribution
      run: V=$(cat VERSION) DZIL_RELEASING=0 dzil build
    - name: Upload to CPAN
      run: cpan-upload -u ${{ secrets.CpanUser }} -p ${{ secrets.CpanPass }} $(ls *.tar.gz)
