name: Testing

on:
  push:
    branches:
    - issue-*
    - milestone-*
    - project-*

jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: perl:5.32

    steps:
    - uses: actions/checkout@v2
    - name: Advertise Perl Version
      run: perl -V
    - name: Install Perl::Critic
      run: cpanm -qn Perl::Critic
    - name: Install Project Dependencies
      run: cpanm -qn --reinstall --installdeps .
    - name: Critiquing Project
      run: perlcritic lib t
    - name: Testing Project
      run: prove -Ilib -r t
      env:
        HARNESS_OPTIONS: j9

  Test-Locale:
    runs-on: ubuntu-latest
    needs:
      - Test
    strategy:
      matrix:
        locale:
        - C
        - C.UTF-8
        - be_BY.UTF-8 # Belarusian
        - de_DE.UTF-8 # German
        - el_GR.UTF-8 # Greek
        - en_GB.UTF-8 # English (UK)
        - en_US.UTF-8 # English
        - es_ES.UTF-8 # Spanish
        - ja_JP.UTF-8 # Japanese
        - pt_BR.UTF-8 # Brazillian
        - ru_RU.UTF-8 # Russian
        - zh_CN.UTF-8 # Chinese

    steps:
    - uses: actions/checkout@v2
    - name: Update Packages Index
      run: sudo apt-get update -y
    - name: Install Locales
      run: sudo apt-get install -y locales locales-all
    - name: Generate Locale
      run: sudo locale-gen ${{ matrix.locale }} >/dev/null | true
    - name: Configure Locale
      run: sudo update-locale LANG=${{ matrix.locale }} LC_ALL=${{ matrix.locale }}
    - name: Advertise Locale
      run: sudo locale
    - name: Advertise Perl Version
      run: perl -V
    - name: Install App::cpanminus
      run: curl -L https://cpanmin.us | sudo perl - App::cpanminus
    - name: Install Project Dependencies
      run: sudo cpanm -qn --reinstall --installdeps .
    - name: Testing Project
      run: sudo prove -Ilib -r t
      env:
        HARNESS_OPTIONS: j9
        LANG: ${{ matrix.locale }}
        LC_ALL: ${{ matrix.locale }}

  Test-Package:
    runs-on: ubuntu-latest
    container:
      image: perl:5.32
    needs:
      - Test
    strategy:
      matrix:
        package:
        - JSON::PP@2.27105
        - Cpanel::JSON::XS@4.09
        - JSON::PP@4.07
        - JSON::XS@3.0
        - YAML::PP::LibYAML@0.004
        - YAML::PP@0.023
        - YAML::XS@0.67

    steps:
    - uses: actions/checkout@v2
    - name: Advertise Perl Version
      run: perl -V
    - name: Install Project Dependencies
      run: cpanm -qn --reinstall --installdeps .
    - name: Install Package ${{ matrix.package }}
      run: cpanm -qn ${{ matrix.package }}
    - name: Testing Project
      run: prove -Ilib -r t
      env:
        HARNESS_OPTIONS: j9

  Test-MacOs:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup GitHub (autocrlf)
      run: git config --global core.autocrlf false
    - name: Setup GitHub (eol)
      run: git config --global core.eol lf
    - name: Setup Perl
      run: brew install perl
    - name: Advertise Perl Version
      run: perl -V
    - name: Install App::cpanminus
      run: brew install cpanminus
    - name: Install Project Dependencies
      run: cpanm -qn --reinstall --installdeps .
    - name: Testing Project
      run: prove -Ilib -r t
      env:
        HARNESS_OPTIONS: j9

  Test-Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup GitHub (autocrlf)
      run: git config --global core.autocrlf false
    - name: Setup GitHub (eol)
      run: git config --global core.eol lf
    - name: Setup Perl
      run: choco install strawberryperl
    - name: Advertise Perl Version
      run: perl -V
    - name: Install App::cpanminus
      run: curl -L https://cpanmin.us | perl - App::cpanminus
    - name: Install Project Dependencies
      run: cpanm -qn --reinstall --installdeps .
    - name: Testing Project
      run: prove -Ilib -r t
      env:
        HARNESS_OPTIONS: j9