name: Testing

on:
  push:
    branches:
    - issue-*
    - milestone-*
    - project-*

jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: perl:5.32

    steps:
    - uses: actions/checkout@v2
    - name: Setup Git User
      run: git config --global user.name "Cpanery"
    - name: Setup Git Email
      run: git config --global user.email "cpanery@cpan.org"
    - name: Setup GitHub User
      run: git config --global github.user ${{ secrets.GithubUser }}
    - name: Setup GitHub Token
      run: git config --global github.user ${{ secrets.GithubToken }}
    - name: Advertise Perl Version
      run: perl -V
    - name: Install Perl::Critic
      run: cpanm -qn Perl::Critic
    - name: Install Project Dependencies
      run: cpanm -qn --reinstall --installdeps .
    - name: Critiquing Project
      run: perlcritic lib t
    - name: Testing Project
      run: prove -Ilib -r t
    - name: Check Documentation
      run: test -n "$(git status --porcelain)" && (git status --porcelain && false) || true
      env:
        HARNESS_OPTIONS: j9
        RENDER: 1

  Variant:
    runs-on: ubuntu-latest
    container:
      image: perl:5.32
    needs:
      - Test
    strategy:
      matrix:
        package:
        - JSON::PP@2.27105
        - Cpanel::JSON::XS@4.09
        - JSON::PP@4.07
        - JSON::XS@3.0
        - YAML::PP::LibYAML@0.004
        - YAML::PP@0.023
        - YAML::XS@0.67

    steps:
    - uses: actions/checkout@v2
    - name: Setup Git User
      run: git config --global user.name "Cpanery"
    - name: Setup Git Email
      run: git config --global user.email "cpanery@cpan.org"
    - name: Setup GitHub User
      run: git config --global github.user ${{ secrets.GithubUser }}
    - name: Setup GitHub Token
      run: git config --global github.user ${{ secrets.GithubToken }}
    - name: Advertise Perl Version
      run: perl -V
    - name: Install Perl::Critic
      run: cpanm -qn Perl::Critic
    - name: Install Project Dependencies
      run: cpanm -qn --reinstall --installdeps .
    - name: Install Package ${{ matrix.package }}
      run: cpanm -qn ${{ matrix.package }}
    - name: Critiquing Project
      run: perlcritic lib t
    - name: Testing Project
      run: prove -Ilib -r t
      env:
        HARNESS_OPTIONS: j9
        RENDER: 1